import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import {BrowserStore,invoiceInput,commitment}from'../public-app/store.mjs';
const data={reference:'INV-1',counterparty:'Design team',description:'A setup guide.',recipient:'0x'+'1'.repeat(40),asset:'ETH',amount:'0.025',tx_hash:'0x'+'2'.repeat(64)};
const make=()=>{const map=new Map();return new BrowserStore({getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)});};
test('browser commitment matches the existing Python commitment format',()=>{const invoice=invoiceInput(data),salt='a'.repeat(64);const python=spawnSync('python3',['-c','import json,sys,store; d=json.load(sys.stdin);print(store.commitment(d["invoice"],d["salt"]))'],{cwd:new URL('..',import.meta.url),input:JSON.stringify({invoice,salt}),encoding:'utf8'});assert.equal(python.status,0);assert.equal(commitment(invoice,salt),python.stdout.trim());});
test('duplicate source transactions and stale reviews are rejected',()=>{const s=make(),r=s.create(data);assert.throws(()=>s.create(data),/already linked/);s.review(r.id,1,{decision:'needs_work',note:'Waiting for evidence.'});assert.throws(()=>s.review(r.id,1,{decision:'needs_work',note:'Old form'}),/changed/);});
test('private data is absent from the default export',()=>{const s=make(),r=s.create(data),out=s.export(r.id);for(const k of ['invoice','salt','review','history','counterparty','description'])assert.equal(k in out,false);assert.equal(s.export(r.id,true).invoice.counterparty,'Design team');});
test('review cannot turn missing or synthetic proof into paid evidence',()=>{const s=make(),r=s.create(data);assert.throws(()=>s.review(r.id,1,{decision:'checked',note:'Looks fine'}),/real inclusion/);const verified=s.update(r.id,1,{receipt:{state:'success'},match:{state:'matched'},inclusion:{state:'verified'}},'Test evidence fixture');assert.equal(s.review(r.id,verified.version,{decision:'checked',note:'Fixture-only review gate test.'}).review.decision,'checked');const sample=s.create(data,true);s.update(sample.id,1,{receipt:{state:'success'},match:{state:'matched'},inclusion:{state:'verified'}},'Synthetic test fixture');assert.throws(()=>s.review(sample.id,2,{decision:'checked',note:'Wrong'}),/real inclusion/);});
test('new unavailable check invalidates review while preserving earlier evidence',()=>{const s=make(),r=s.create(data);s.update(r.id,1,{receipt:{state:'success'},match:{state:'matched'},inclusion:{state:'verified'},review:{decision:'unreviewed',note:''}},'First');s.review(r.id,2,{decision:'checked',note:'Checked evidence.'});const latest=s.update(r.id,3,{receipt:{state:'unavailable'},match:{state:'unknown'},inclusion:{state:'unknown'},review:{decision:'unreviewed',note:'Checked evidence.'}},'Unavailable');assert.equal(latest.review.decision,'unreviewed');assert.equal(latest.checks.length,2);assert.equal(latest.checks[0].inclusion.state,'verified');});
test('private backup restores the commitment but never trusts imported network checks',()=>{const source=make(),r=source.create(data);source.update(r.id,1,{receipt:{state:'success'},match:{state:'matched'},inclusion:{state:'verified'},registry:{state:'recorded'}},'Untrusted test values');const bundle=source.export(r.id,true),target=make(),restored=target.restore(bundle);assert.equal(restored.commitment,r.commitment);assert.equal(restored.receipt.state,'unknown');assert.equal(restored.registry.state,'recovery');assert.equal(restored.review.decision,'unreviewed');assert.throws(()=>make().restore({...bundle,invoice:{...bundle.invoice,amount:'100'}}),/commitment/);assert.throws(()=>make().restore(source.export(r.id)),/private backup/);});

test('private restore preserves notes and recovery hints without trusting claimed publication',()=>{const source=make(),r=source.create(data);source.review(r.id,1,{decision:'needs_work',note:'Ask for the revised invoice.'});source.update(r.id,2,{registry:{state:'pending',hash:null,from:'0x'+'3'.repeat(40),nonce:4,startBlock:100,data:'untrusted calldata',digest:'untrusted digest'}},'Fixture intent');const restored=make().restore(source.export(r.id,true));assert.equal(restored.review.note,'Ask for the revised invoice.');assert.equal(restored.review.decision,'unreviewed');assert.equal(restored.registry.state,'recovery');assert.equal(restored.registry.nonce,4);assert.equal(restored.registry.data,undefined);assert.equal(restored.registry.digest,undefined);assert.equal(restored.inclusion.state,'unknown');});
test('invalid restoration hints do not partially create a record',()=>{const source=make(),r=source.create(data),bundle=source.export(r.id,true),target=make();bundle.registry={state:'recorded',hash:'bad hash'};assert.throws(()=>target.restore(bundle),/transaction hash/);assert.equal(target.all().length,0);});

test('private restore writes the original commitment and recovery hints atomically',()=>{const source=make(),r=source.create(data),bundle=source.export(r.id,true),writes=[];const target=new BrowserStore({getItem:()=>null,setItem:(key,value)=>writes.push(JSON.parse(value))});target.restore(bundle);assert.equal(writes.length,1);assert.equal(writes[0][0].commitment,bundle.commitment);assert.equal(writes[0][0].salt,bundle.salt);});
