import test from 'node:test';import assert from 'node:assert/strict';import{keccak256,ZeroHash}from'ethers';import{Registry}from'../public-app/registry.mjs';import{BrowserStore}from'../public-app/store.mjs';
const from='0x'+'1'.repeat(40),to='0x'+'2'.repeat(40),hash='0x'+'3'.repeat(64),id='0x'+'4'.repeat(64);
function setup(){const m=new Map(),store=new BrowserStore({getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)});let r=store.create({reference:'TEST',counterparty:'Fixture',description:'Mock provider test only',recipient:from,amount:'1',asset:'ETH',tx_hash:hash});r=store.update(r.id,1,{receipt:{state:'success',block:10},match:{state:'matched'},inclusion:{state:'verified',encoded_hash:keccak256('0x1234'),proof:{chainKey:1,headerNumber:10,txIndex:0,txHash:hash,txBytes:'0x1234',merkleProof:{root:ZeroHash,siblings:[]},continuityProof:{lowerEndpointDigest:ZeroHash,roots:[]}}}},'Fixture');const provider={send:async()=> '0x18e8f',getCode:async()=> '0x6000',estimateGas:async()=>100000n,getTransactionCount:async()=>7,getBlockNumber:async()=>100};const registry=new Registry(store,provider,{registry:to,codeHash:keccak256('0x6000'),explorer:'https://creditcoin-testnet.blockscout.com'});return{store,r,registry,provider};}
test('registry refuses wrong chains, bytecode, and modified source proof',async()=>{const{registry,r,provider}=setup();provider.send=async()=> '0x1';await assert.rejects(registry.check(),/wrong chain/);provider.send=async()=> '0x18e8f';provider.getCode=async()=> '0x6001';await assert.rejects(registry.check(),/code differs/);r.inclusion.proof.txHash=ZeroHash;assert.throws(()=>registry.prepare(r),/different source/);});
test('uncertain wallet send persists exact intent and cannot be submitted again',async()=>{const{registry,r,store,provider}=setup();const signer={provider,getAddress:async()=>from,sendTransaction:async()=>{throw Error('Connection lost');}};await assert.rejects(registry.send(r.id,r.version,signer),/Connection lost/);const current=store.get(r.id);assert.equal(current.registry.state,'pending');assert.equal(current.registry.nonce,7);assert.equal(current.registry.commitment,r.commitment);await assert.rejects(registry.send(r.id,current.version,signer),/already has/);});
test('explicit wallet rejection clears an unsent intent',async()=>{const{registry,r,store,provider}=setup();await assert.rejects(registry.send(r.id,r.version,{provider,getAddress:async()=>from,sendTransaction:async()=>{throw Object.assign(Error('Rejected'),{code:4001});}}),/Rejected/);assert.equal(store.get(r.id).registry.state,'not_recorded');});
test('receipt recovery binds sender, nonce, value and calldata before applying a real event',async()=>{const{registry,r,store,provider}=setup();const data=registry.prepare(r);store.update(r.id,r.version,{registry:{state:'pending',from,to,data,nonce:7,startBlock:100,hash,commitment:r.commitment,digest:r.inclusion.encoded_hash}},'Test pending');const log=registry.iface.encodeEventLog(registry.iface.getEvent('InclusionRecorded'),[id,from,r.commitment,1,10,0,r.inclusion.encoded_hash]);provider.getTransaction=async()=>({from,to,nonce:7,data,value:1n});provider.getTransactionReceipt=async()=>({status:1,blockNumber:101,logs:[{address:to,...log}]});await assert.rejects(registry.reconcile(r.id),/differs/);provider.getTransaction=async()=>({from,to,nonce:7,data,value:0n});provider.call=async()=>registry.iface.encodeFunctionResult('records',[from,r.commitment,r.inclusion.encoded_hash,10,0,100]);const done=await registry.reconcile(r.id);assert.equal(done.registry.state,'recorded');assert.equal(done.registry.record_id,id);assert.equal((await registry.reconcile(r.id)).version,done.version);});
test('mined revert is recorded without claiming successful publication',async()=>{const{registry,r,store,provider}=setup(),data=registry.prepare(r);store.update(r.id,r.version,{registry:{state:'pending',from,to,data,nonce:7,startBlock:100,hash,commitment:r.commitment,digest:r.inclusion.encoded_hash}},'Test pending');provider.getTransaction=async()=>({from,to,nonce:7,data,value:0n});provider.getTransactionReceipt=async()=>({status:0,blockNumber:101});assert.equal((await registry.reconcile(r.id)).registry.state,'reverted');});

test('wallet hash recovers a pending transaction older than the automatic scan',async()=>{const{registry,r,store,provider}=setup(),data=registry.prepare(r);store.update(r.id,r.version,{registry:{state:'pending',from,to,data,nonce:7,startBlock:100,hash:null,commitment:r.commitment,digest:r.inclusion.encoded_hash}},'Fixture intent');provider.getBlockNumber=async()=>1000;provider.send=async method=>method==='eth_chainId'?'0x18e8f':{transactions:[]};await assert.rejects(registry.reconcile(r.id),/last 128 blocks/);provider.getTransaction=async()=>({from,to,nonce:7,data,value:0n});provider.getTransactionReceipt=async()=>({status:0,blockNumber:101});assert.equal((await registry.reconcile(r.id,hash)).registry.state,'reverted');});
test('restored registry hints require fresh proof and matching invoice calldata',async()=>{const{registry,r,store,provider}=setup(),data=registry.prepare(r);store.update(r.id,r.version,{registry:{state:'recovery',hash,from},inclusion:{state:'unknown'}},'Imported hints');await assert.rejects(registry.reconcile(r.id),/real inclusion/);store.update(r.id,3,{inclusion:r.inclusion},'Fresh proof fixture');provider.getTransaction=async()=>({from,to,nonce:7,data:registry.iface.encodeFunctionData('record',[ZeroHash,1,10,'0x1234',r.inclusion.proof.merkleProof,r.inclusion.proof.continuityProof]),value:0n});provider.getTransactionReceipt=async()=>({status:0,blockNumber:101});await assert.rejects(registry.reconcile(r.id),/freshly checked/);provider.getTransaction=async()=>({from,to,nonce:7,data,value:0n});assert.equal((await registry.reconcile(r.id)).registry.state,'reverted');});
