import {build} from 'esbuild';
import {mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
await mkdir('dist/fonts',{recursive:true});
let app=await readFile('web/app.js','utf8');
app="import {registryPanel} from '../public-app/registry-ui.mjs';\nimport {browserFetch as fetch,download} from '../public-app/transport.mjs';\n"+app;
app=app.replaceAll('Invoice details stay on this Mac.','Invoice details stay in this browser. Export a private backup before clearing browser data.').replaceAll('Start the local Docket service, then refresh this page.','The browser workspace could not open. Check storage access and refresh.').replaceAll('Check the local service and refresh.','Check browser storage and refresh.');
app=app.replace('<button class="quiet" data-ui="sample">Open a synthetic example</button>','<button data-ui="example">Open a real public transfer example</button><button class="quiet" data-ui="sample">Open a synthetic example</button>');
app=app.replace("if(action==='sample')send('/api/sample',{});","if(action==='sample')send('/api/sample',{});if(action==='example')send('/api/example',{});");
const registryStart=app.indexOf('<details><summary>Public registry status:');
const registryEnd=app.indexOf('</details>',registryStart)+10;
if(registryStart<0||registryEnd<10)throw Error('Registry view hook changed.');
app=app.slice(0,registryStart)+'${registryPanel(r,esc)}'+app.slice(registryEnd);
app=app.replace("if(action==='sample')", "if(['publish','reconcile'].includes(action)){const r=records.find(r=>r.id===selected);send('/api/'+action,{id:r.id,version:r.version,hash:action==='reconcile'?document.querySelector('#registry-recovery-hash')?.value.trim():undefined});}if(action==='sample')");
app=app.replace('}catch(e){say(e.message,true);localFeedback', '}catch(e){await load().catch(()=>{});say(e.message,true);localFeedback');
app=app.replace('<label class="search">', '<label class="backup">Restore private backup<input id="restore-backup" type="file" accept="application/json,.json"></label><label class="search">');
app+="\napp.addEventListener('change',async e=>{if(e.target.id!=='restore-backup')return;try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Backup is larger than 5 MB.');await send('/api/restore',{bundle:JSON.parse(await file.text())});}catch(error){say(error.message,true);}});\n";
app+="\napp.addEventListener('click',e=>{const a=e.target.closest('a[href^=\"/api/export/\"]');if(!a)return;e.preventDefault();const url=new URL(a.href);try{download(url.pathname.split('/').at(-1),url.searchParams.get('private')==='1');}catch(error){say(error.message,true);}});\n";
await build({stdin:{contents:app,resolveDir:new URL('../web',import.meta.url).pathname,sourcefile:'public-app.mjs'},bundle:true,format:'esm',minify:true,outfile:'dist/app.js',target:'es2022',define:{'process.env':'{}'},legalComments:'eof'});
let html=(await readFile('web/index.html','utf8')).replaceAll('href="/"','href="./"').replace('href="/style.css"','href="style.css"').replace('<script src="/app.js" defer>','<script type="module" src="app.js">').replace('Private local workspace','Private browser workspace');
html=html.replace('<title>',`<meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; connect-src https://ethereum-sepolia-rpc.publicnode.com https://rpc.cc3-testnet.creditcoin.network https://prover.cc3-testnet.creditcoin.network; img-src 'self' data:; object-src 'none'; base-uri 'none'; form-action 'self'"><title>`);
await writeFile('dist/index.html',html);await writeFile('dist/style.css',(await readFile('web/style.css','utf8')).replaceAll('/fonts/','fonts/'));await writeFile('dist/.nojekyll','');
for(const weight of [400,500,600,700])await copyFile(`node_modules/@fontsource/public-sans/files/public-sans-latin-${weight}-normal.woff2`,`dist/fonts/public-sans-${weight}.woff2`);
console.log('Built private browser workspace. No private server or invoice records are published.');
await mkdir('dist/licenses',{recursive:true});
await copyFile('node_modules/@fontsource/public-sans/LICENSE','dist/licenses/Public-Sans.txt');
await copyFile('node_modules/ethers/LICENSE.md','dist/licenses/ethers.md');
await copyFile('THIRD-PARTY.md','dist/licenses/THIRD-PARTY.md');
